create database videojuegos;
use videojuegos;

create table juegos(id_juego int AUTO_INCREMENT, nombre varchar(150), anio int(4), desarrollador varchar(150), PRIMARY KEY(id_juego));
ALTER TABLE juegos convert to character set utf8;
INSERT INTO juegos (nombre, anio, desarrollador) VALUES ('Hot Wheels Stund Track Driver',1998,'Semi Logic Entertainments'), 
												  ('Red Dead Redemption 2',2018,'Rockstar Games'),
												  ('Red Dead Redemption',2010,'Rockstar Games'),   
												  ('LEGO Batman',2008,'Travellers Tales'),
												  ('Secret Agent Clank',2008,'High Impact Games'),
												  ('Mortal Kombat 9',2011,'Warnes Bros Games'), 
												  ('Crash Bandicoot',1996,'Naughty Dog'), 
												  ('Sonic the Hedgehog',1991,'SEGA'), 
												  ('Devil May Cry',2001,'Capcom'), 
												  ('DOOM',1993,'ID Software'), 
												  ('Injustice: Gods Among Us',2013,'NetherRealm Studios'),
												  ('Grand Theft Auto: San Andreas',2004,'Rockstar Games'),  
												  ('Halo: Combat Evolved',2001,' Microsoft Game Studios'),  
												  ('Batman: Arkham Knight',2015,'Rocksteady Studios'),
												  ('Castlevania: Symphony of the Night',1997,'Konami'),  
												  ('Silent Hill Homecoming',2008,'Team Silent,Konami'),  
												  ('Ikaruga',2001,'Treasure Co. Ltd'),  
												  ('Metal Slug 3',2000,'SNK'),  
												  ('Metal Gear Solid 2: Sons of Liberty',2001,'Konami'),  
												  ('Super Metroid',1994,'Nintendo'),
												  ('The Legend of Zelda',1987,'Nintendo'),  
												  ('Conkers Bad Fur Day',2001,'Rare'),
												  ('Gears of War 3',2011,'Epic Games'),
												  ('Dark Souls',2011,'From Software'),
												  ('Bloodborne',2015,'From Software'),
												  ('Resident Evil 2',1998,'Capcom'),
												  ('Outlast',2013,'Red Barrels Studio'),
												  ('Yu-Gi-Oh! Forbidden Memories',1999,'Konami'),
												  ('WALL-E',2008,'THQ'),
												  ('Prince of Persia: Las dos coronas',2005,'Ubisoft'),
												  ('Cyberpunk 2077',2020,'CD Projekt'),
												  ('Plants VS. Zombies',2009,'PopCap Games'),
												  ('Saints Row IV',2013,'Volition Inc.'),
												  ('Bully',2006,'Rockstar Vancouver'),
												  ('Final Fantasy VIII',1999,'Square-Enix'),
												  ('Space Invaders',1978,'Midway Games'),
												  ('Pac-Man',1980,'Midway Games'),
												  ('Lollipop Chainsaw',2012,'Grasshopper Manufacture'),
												  ('Bomberman',1983,'Hudson Soft'),
												  ('Scott Pilgrim vs. the World: The Game',2010,'Ubisoft'),
												  ('League of Legends',2009,'Riot Games'),
												  ('Bayonetta',2009,' PlatinumGames');
												  ('Cuphead',2017,'Studio MDHR'),
												  ('Adventure',1979,'Warren Robinett'),
												  ('Tetris',1984,'Alekséi Pázhitnov');